### ISSUE TITLE
Incluir repositórios 

### ISSUE THREAD

**Issue by guibranco** [LarissaAbreu/contrata-se-dev#23]
Incluir os repositórios abaixo no projeto:

#### Por área

- [Vagas para desenvolvedores Back-End](https://github.com/backend-br/vagas)
- [Vagas para desenvolvedores Front-End](https://github.com/frontendbr/vagas)
- [Vagas para QAs](https://github.com/qa-brasil/vagas)

#### Por tecnologia

- [Vagas para desenvolvedores Android](https://github.com/androiddevbr/vagas)
- [Vagas para desenvolvedores iOS e OSX](https://github.com/CocoaHeadsBrasil/vagas)
- [Vagas para desenvolvedores PHP](https://github.com/phpdevbr/vagas)
- [Vagas para desenvolvedores Python](https://pyjobs.com.br)
- [Vagas para desenvolvedores Vue.js](https://github.com/vuejs-br/vagas)
- [Vagas para desenvolvedores Go/Golang](https://github.com/Gommunity/vagas)
- [Vagas para Flutter](https://github.com/flutter-brazil/vagas)
- [Vagas para React/React Native](https://github.com/react-brasil/vagas)
- [Vagas para desenvolvedores .NET](https://github.com/dotnetdevbr/vagas)
- [Vagas para desenvolvedores Rust](https://github.com/rustdevbr/vagas)

#### Por localidade

- [Vagas para desenvolvedores no Ceará](https://github.com/CangaceirosDevels/vagas_de_emprego)
- [Vagas para desenvolvedores em Salvador](https://github.com/devssa/onde-codar-em-salvador)
- [Vagas para desenvolvedores Front-end (Angola)](https://github.com/frontend-ao/vagas)
- [Vagas para desenvolvedores Back-end (Angola)](https://github.com/backend-ao/vagas)
- [Vagas para desenvolvedores Front-end (Portugal)](https://github.com/frontend-pt/vagas)
- [Vagas para desenvolvedores Back-end (Portugal)](https://github.com/backend-pt/vagas)

**Comment by guibranco** [comment]
@LarissaAbreu

**Comment by LarissaAbreu** [comment]
Ooooie, @guibranco . Tudo bem? Eu amei a ideia! Não tinha esses links! Agora a ideia é arranjarmos um jeito de incluir esses repositórios no projeto. Tu tem alguma sugestão?

Aqui no [Roadmap](https://github.com/LarissaAbreu/contrata-se-dev/issues/2) eu citei alguns critérios pra podermos adicionar vagas de outros repositórios também.
