### ISSUE TITLE
When to click in 'Mostrar mais' button, show a loading interaction 

### ISSUE THREAD

**Issue by natansevero** [LarissaAbreu/contrata-se-dev#4]
I think that would be cool show a loading interaction when the user to click in 'Mostar mais' button. This only a little bit interaction :)
Can I open a pull request with that, pls?

**Comment by LarissaAbreu** [comment]
Hy, @natansevero ! It's a awesome ideia! Please open a PR with your code solution.

Ps.: Do not forget to take a look at the [contribution instructions](https://github.com/LarissaAbreu/contrata-se-dev/blob/master/CONTRIBUTING.md)
