### ISSUE TITLE
Repo

### ISSUE THREAD

**Issue by devssa** [LarissaAbreu/contrata-se-dev#6]
Boa noite tudo certinho? Muito bacana o sistema :)

Tenho um repo onde-codar-em-salvador, como faço pra seu site exibir as vagas de lá? Forkei do front-end br

**Comment by LarissaAbreu** [comment]
@devssa oie, por aqui tudo bem :) e por aí? Fico feliz em ter gostado do projetinho hehehe

Eu não sabia desse seu repo rs parabéns pela iniciativa!

Para exibir as vagas de lá do seu repo podemos fazer de duas maneiras... 1- se quiser você pode se sentir à vontade para fazer um fork aqui do projeto e colocar suas alterações nele (seguindo o guia de contribuiçãr rs); 2- se preferir, eu posso trabalhar nisso e colocar as vagas daí para aparecerem lá também xD

Me diz o que prefere e se precisar de algum help pode me chamar no [twitter](https://twitter.com/TheSweet_Lari) ♥

**Comment by devssa** [comment]
seria massa ter o conteudo no seu portal, ficariamos lisonjeados :)

**Comment by devssa** [comment]
oi @LarissaAbreu como vai? já faz algum tempo desde a ultima update desta issue...
Criamos o portal e fizemos questão de te citar, olha e vê se esquecemos alguma coisa...

https://codar.app

Iremos subir os fontes pro repo e tornar publico na proxima semana, open source é amor :D

Obrigado por ter criado esse produto supimpa, vc é daora

**Comment by LarissaAbreu** [comment]
@devssa ficou demais! 💙

Me desculpa por não ter atualizado nada aqui.. é que o bixo tá pegando no trabalho e em outros projetos e acabei não tendo tempo para estudar sobre como se faz uma API para tratar mais de um repo no site =/

Mas nossa, parabéns mesmo! Eu amei!!!
