### ISSUE TITLE
[Vagas na Zona Sul de São Paulo] - Data Engineer Sênior

### ISSUE THREAD

**Issue by natashacosta** [LarissaAbreu/contrata-se-dev#7]
Oi, pessoal!
Tudo bem? :)

Sou Tech Recruiter na K2 Partnering, consultoria de recrutamento e seleção britânica, presente em 19 países, há mais de 20 anos. Trabalhamos fortemente com busca por realocação e fazemos todo um acompanhamento da evolução do profissional, através de contato constante e visitas ao cliente. Temos clientes de diversos segmentos, contratações/parcerias CLT e PJ ou como funcionário do próprio cliente.

Temos duas vagas de Data Engineer Senior para atuar num cliente, na região do Morumbi. Este, é uma multinacional americana, com mais de 150 anos e que já está no Brasil há 50. Sua atividade é a produção e o processamento de alimentos. O fit perfeito seria com profissionais que queiram atuar de forma multicultural (pensando no globo), estando aberto a um ambiente inovador, cheio de reais possibilidades de desenvolvimento de carreira. 

Pré-requisitos:

-	Impala / Kudu (SQL)
-	Shell Script
-	Modelagem Dimensional
-	Sqoop
-	Performance Tuning de queries impala
-	Spark
-	Python, Java, ou Scala
-	Tunning e performance de queries
-	Inglês avançado/fluente

Parceria PJ, com a K2. Projeto até Abril/2020, podendo estender, no final do mesmo buscaríamos realocação, sempre de acordo com o que for mais interessante para o profissional. 

Tem interesse? Me procura!!

ncosta@k2partnering.com
(11) 9 9820 6781 | Mobile (WhatsApp)

**Comment by LarissaAbreu** [comment]
Oi @natashacosta tudo bem? Então... esse projeto aqui apenas lista vagas cadastradas no [repositório de vagas do Front-end BR](https://github.com/frontendbr/vagas/issues)... futuramente incluiremos vagas cadastradas em outros repositórios também :)
